[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "0c6f32fe0fdc401d38a1d4a8b60e497a095c816e"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "29dd0a8a26a75ac777720df2c8fa3bfce5d380ed1d454cba4d2c50db9cc77232"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "11794a07641628962fbd4b66e5d7a3d8c3bcdd1d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "de70fd5e7c8121fd130a3f404f1e4673e04fe386de8bf08afd63de94f61c7518"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "64b72cdd86b7894082bf68863b52d8f377ec1f88"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "38b5fbc4453ca3508ecef8ac1c3e2b4d9507a027ae3582ff2de7d238fee2aa05"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.aarch64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "powerpc64le"
git-tree-sha1 = "e6e6fc252d3456d66b6243c80c4530e682a896ed"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "bb78f3dd978c59146b47d33968ec9ddea8234cca2bd5b833c51628c7af4df26f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "9cda5bf5fae8e73c586c5deb1bb28a51b1bb25b4"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "b82d403756edfc4380a79a44eb21ad0545284170b9ac5d60bcac194291a762c3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "c773ddbcd33f48d9f95b0b0dce5d8cee0afc0942"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "5e5bade54da1a7e4c8c51127972789c83a750c988222e88198095bb6ffd7224d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "be7a19e80bae42615343f948eadce4c72ef322a8"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "f75fda088c43255f384dd1375dbc67325fed31366c07570b0393528a0084fc3f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.x86_64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "596076edfecb17426fb43e7c13b0cd2547eedc8c"
os = "freebsd"

    [[GAP_pkg_crypting.download]]
    sha256 = "84b882b2d6f57fb33b6949fadc0cb69e643ffa3d0259e6b2ef6e02f3d021c8b4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.402+0/GAP_pkg_crypting.v0.1000.402.x86_64-unknown-freebsd.tar.gz"
