[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "f99bd499238ec39cf10499765c6ebf43e7ecd9c6"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "de862c73ad699185444cf6c4472b5b01c8139fa97ea0eafea68e46328686581d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "6d4405540de8e5c64bc50f96316b7e2a613fd9e1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "9a782353caee42c5e63d1fd4eb051cdb1406e11d6ac8edb0dbf37d48d268cc64"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "bd35838b8ad84d36baa34ad212f8cc68a9f93a76"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "680b6dfaa52f19f9b8ce89dbc76e1cc595b2f1da1869d3fc7b541c16d084370b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.aarch64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "838cd4d5af42d6a371c2caef7cdc6eeccfc3bebb"
os = "freebsd"

    [[GAP_pkg_crypting.download]]
    sha256 = "9a8833badc576fa0b236c57e8bfbb9902ab0fc9c778400547f469c15a60983e3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_crypting]]
arch = "powerpc64le"
git-tree-sha1 = "895cf2eb894409cf3513fe47bbc3d66e40f789d5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "07946710b12a7598ecc9f970ff746d69fcd19b8c29f3c5ce63d40da3445c82ce"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "riscv64"
git-tree-sha1 = "0bff1a8a643df05765f3376fd59933555877b7fc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "7725ab4e45e4539f77bfcc3de847fbba1b6e0314a54d94a0c66e790161bd39b0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "3b13319b0c8577dcedd175baffdf5c3bf6d42539"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "43b8b41ae0d47f417965ea24a56149bc09133061d53a3197584f7eff512b5c43"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "89863a6998d6a9b368c87717d022d5efcb565179"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "5a1f77d02dd3012c9945dce337b92621d43231fbb2255b6960b62dc1013244bb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "a461b9c7ccee14433f2658cc1b2d3147d31d0e6e"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "e4c612c5da9a9b02b9be7ce8a79781785b717349fd940bceef580f292ee75822"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.x86_64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "066962a3ce711ccb009c436e639a8d46e368a6d2"
os = "freebsd"

    [[GAP_pkg_crypting.download]]
    sha256 = "ff40906ed937467ced23b1997844fc96b5d2eed4278f32e5767d880f479be2ab"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.502+0/GAP_pkg_crypting.v0.1000.502.x86_64-unknown-freebsd.tar.gz"
