[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "29de4a276145040e1ad55026376826c70d2a5b8d"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "392d470f7b68db3a6f0e304c932261c6fe987931ceb47bbe8f26642a55e67f57"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "3cfb6486b1d0c6829708564bd2151831338df2a2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "f4d30268f29ca10f85f07ced6d434c9421045cc73fc676b896c4698960b10bb3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "5bb306727ac424790788b87bd9de4e44c1dd2a43"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "8c945373f4367a86b279a34aedcd9b97b35e8f6af5845b5a88dc21bd17c415b8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.aarch64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "d4de8fee560e202815a927672fa5741b44e30385"
os = "freebsd"

    [[GAP_pkg_crypting.download]]
    sha256 = "0747315fdd827397ef01fc7153a7b9f79645c66d8c8f3acd11edefb3ab0819c1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_crypting]]
arch = "powerpc64le"
git-tree-sha1 = "db44807da51e6400bd07bf841009aa432c0c4ca1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "9e98db7b3562b71ae162a9c7140bb1e44a6e6c60e10aa05e412a9f201f21978d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "riscv64"
git-tree-sha1 = "86ef1a87d0e9eaf1f253483e7b36a0ba9dbd9d0a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "f88b34919c51a774cf03dbc39c702b98fadc9a5685ad737c8a15506a41e78271"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "5a3b9f8392cd6ef78ca5d5c4c65e18602aaf2116"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "a0fc0d2ccd633e871b8e539a8b91700e10fdadab1667960f083760ea312cd7d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "2afb227eaf750e6ecf4be2a201c1d8ee24686f6d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "52e54e642cdcc8f5fae7f2766fcec952c010679ecb0a063021413984bc5c0eeb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "ab90459419b5f4cb5e010a2df7be22f21187ecfe"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "82b7ef8badb13ee5c25c7e44e5c9d4601da2003a9c9362613ce439ea7e9009fd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.x86_64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "fb1072acacc7bd22a85c933b05db170bc34d42e9"
os = "freebsd"

    [[GAP_pkg_crypting.download]]
    sha256 = "35f7f1498902fa408c19850d9f947b374d9f5b46f13c4ac74d5bd81abc8239be"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.501+0/GAP_pkg_crypting.v0.1000.501.x86_64-unknown-freebsd.tar.gz"
