[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "ea0f139ea9c5d956374360c4da95b6e72792c6b7"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "24f80ea04b4e63fc2bbd5f8c33ab5cfd63c76c3cee896f46cbffff9ffee4454c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "bd9dbc1488f7fbcc05ba80ddedc29f3ff23ad813"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "8e67a1909c3dd973204e1fabc0d8e08146ba618c5510978d82755a3a28172b68"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "5a313cf7dddd88c38b0477c23f39a06e47d6e651"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "630401cc02da281a74026ccfb2b2a5f0295570d63a8357b2f72bd5a17248d92a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.aarch64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "powerpc64le"
git-tree-sha1 = "5384a2b9beb94ef788789dcb051ac04f9a40e978"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "6357282ef6f85079317e9d964a4d4b52424711077573f5eb0bd386fab74e2d0b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "c8527da9198a5c142f9d141c357a0b0ed47d5760"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "c0e478f139f25545db1e48a3f8810b78a7a5cb0e31db6ecc36b0f0855f2ecdcc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "290aebdc89f03e9b3bd67b7ba15014122ad31774"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "1332750e6e60fbb1497fd87174d932c7a09f27d15f7f0be0cf75d95f761c93d4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "6729b550981b0d12d8311c19e365cf9569c09286"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "bb4185b37cdd481b7e6d3b2ad118d8e6a65bcc7dd17269f900887052c7fed230"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.x86_64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "dc6dd4ceb9a6df2203ee67918d823b420f2d11c5"
os = "freebsd"

    [[GAP_pkg_crypting.download]]
    sha256 = "fde2a066d2a4a53d34f84586e687dc0bc8df2102d8cbee2683c0d39e3271eebd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+0/GAP_pkg_crypting.v0.1000.500.x86_64-unknown-freebsd.tar.gz"
