[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "4abd4f8b1fd9831651e3cce2034f3c21da76d2cd"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "8f20a939174e04ecfaa5481b76be5b941a42a1aeb2ed95016e5bc018bbbf3d50"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "1e1f17807cfef4b6c026f7b35b01a96bf5e88cb7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "0719a7e62d6ee711b1e56fd86991afb9209f144ac579c596b299f8f927ef2227"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "aarch64"
git-tree-sha1 = "05e0d410cf6269f7a4bfb709ea20c11c630e419d"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "cad13b19eaff314597ac76547344441ce8f1bf0fb4c3ff9936a597525a286ca9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.aarch64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "powerpc64le"
git-tree-sha1 = "11c6240c86efb0a2496be75b59fd2d8fe62ce16d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "db067f3c5b2fca267489fa95511c2c294057e8e86df359e48f10d03015a0944e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "5a731608f0ae0e60c44f9cf0009d8014128719f6"
os = "macos"

    [[GAP_pkg_crypting.download]]
    sha256 = "5dfdd2387533002fded1552a495f2f7a5281931ca130e99f505b85945f9841d7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "82ef20c025cfdd19a368393f5c5f7428a883a688"
libc = "glibc"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "94040d2935224c7547ceaed423d826a8b44056dcca27217cab327c283aa92233"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "c4da17c97dfeb0b7e7d58cd24c45d55efffce207"
libc = "musl"
os = "linux"

    [[GAP_pkg_crypting.download]]
    sha256 = "48dd109c3cdf96001f324e625a5c5c514a5a6eb10d2dcb81e840c01f3462ccd4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.x86_64-linux-musl.tar.gz"
[[GAP_pkg_crypting]]
arch = "x86_64"
git-tree-sha1 = "11348e47d324a213913ef7055fa45659784b507d"
os = "freebsd"

    [[GAP_pkg_crypting.download]]
    sha256 = "6ccbdacc4b351435b945c63127c0cb5e8e5a4c70d4dc2f0f7f4ea559448c696e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_crypting_jll.jl/releases/download/GAP_pkg_crypting-v0.1000.500+1/GAP_pkg_crypting.v0.1000.500.x86_64-unknown-freebsd.tar.gz"
